# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"
  
  - script: |
      npm test -- src/test/HouseContext.test.js --watchAll=false --reporters=default --reporters=jest-junit || exit 1
    displayName: "Run House context unit test"
  
  - script: |
      npm test -- src/test/Login.test.js --watchAll=false --reporters=default --reporters=jest-junit || exit 1
    displayName: "Run Login and Google Login unit test"

  - task: PublishTestResults@2
    displayName: 'supply npm test results to pipelines'
    condition: succeededOrFailed() 
    inputs:
      testResultsFiles: 'src/test/junit.xml'


