# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"
  
  - task: NPM@1
    inputs:
      command: "custom"
      workingDir: "src/test"
      customCommand: "test -- src/test/HouseContext.test.js"
    displayName: "Run House context unit test"



